import Head from "next/head";

import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import elder from "../public/vanhus.jpg";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Oskarin It </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h2 className="font-burtons text-x1">Oskarin-It</h2>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>

              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="./tietosuoja"
                >
                  Tietosuoja
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Oskarin IT-tuki
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              It tukea senioreille.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Tervetuloa Oskarin IT-tuen nettisivuille! Oskarin IT-tuki tarjoaa
              teknistä tukea ja opastusta seniori-ikäisille. Tarjoamme myös apua
              ohjelmistojen käytössä, teknisissä ongelmissa ja järjestämme
              koulutuksia.
            </p>

            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Oskarin IT-tuki on perustettu vuonna 2023.
            </p>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <section className="min-h-screen">
            <div className="text-center p-10 py-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
                Oskarin-IT paikan päällä tapahtuva tuki: Hinta: 25€/tunti
              </h2>
              <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
                Palvelun kuvaus: Oskarin-IT tarjoaa asiantuntevaa IT-apua ja
                opastusta senioreille heidän tarpeidensa mukaan. Avustus voi
                kattaa esimerkiksi tietokoneiden, älypuhelinten, ohjelmistojen,
                internet-yhteyksien ja muiden laitteiden käytön ja
                ongelmanratkaisun.
              </h3>
              <p className="text-md py-5 leading-8 text-teal-800 dark:text-teal-200 max-w-xl mx-auto md:text-xl">
                Palvelun sisältö:
              </p>

              <ul className="text-3xl py-2 text-teal-600 dark:text-teal-400 md:text-1">
                <li>IT-laitteiden käytön opastus</li>
                <li>Ohjelmistojen asennus ja päivitykset</li>
                <li>Tietoturva- ja virusongelmien ratkaisu</li>
                <li>Internet-yhteyksien asetukset ja vianmääritys</li>
                <li>Sähköpostin ja sosiaalisen median käytön opastus</li>
                <li>Ongelmanratkaisu ja kysymysten selvittäminen</li>
                <li>Yleinen IT-neuvonta ja tuki</li>
              </ul>

              <ul className="text-3xl py-2 text-grey-600 dark:text-red-400 md:text-1">
                <li>Ota yhteyttä, mieluiten Whatsapin kautta :) </li>
                <li> +358443609007 </li>
              </ul>
            </div>
          </section>

          <div className="lg:flex gap-10"></div>
        </section>
      </main>
    </div>
  );
}
